[package]
name = "meerkat"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
auto_update.workspace = true
chrono.workspace = true
db_client.workspace = true
db_postgres.workspace = true
fuzzy.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
gpui_tokio.workspace = true
introspect.workspace = true
query.workspace = true
release_channel.workspace = true
results_grid.workspace = true
secrets.workspace = true
sql_editor.workspace = true
storage.workspace = true
theme.workspace = true
ui.workspace = true
